name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    name: Lint
    if: "!contains(github.event.head_commit.message, 'noci')"
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v5

      - name: prepare
        run: |
          touch internal/js/qjs.wasm

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

  lint-jsonschema:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'noci')"
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: actions/checkout@v5

      - name: install check-jsonschema
        run: python -m pip install 'check-jsonschema==0.27.3'

      - name: check-jsonschema (metaschema)
        run: check-jsonschema --check-metaschema website/src/public/schema.json
