name: Test

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - uses: robinraju/release-downloader@v1
        with:
          repository: "ssuf1998dev/task-quickjs-ng"
          tag: "v0.6.0"
          fileName: "qjs.wasm"
          out-file-path: "internal/js"

      - name: Build
        run: go build -o ./bin/task -v ./cmd/task

      - name: Test
        run: ./bin/task test --output=group --output-group-begin='::group::{{.TASK}}' --output-group-end='::endgroup::'
