name: Test

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
        id: nodejs

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build civet for interpreting
        working-directory: internal/interpreter/civet
        run: |
          git config --global core.autocrlf input
          git submodule init
          git submodule update
          cd Civet
          git apply ../build.patch
          yarn install
          yarn build
          yarn terser dist/quickjs.mjs --compress --mangle --ecma 2015 --output dist/quickjs.min.mjs

      - name: Build
        run: go build -o ./bin/task -v ./cmd/task

      - name: Test
        run: ./bin/task test --output=group --output-group-begin='::group::{{.TASK}}' --output-group-end='::endgroup::'
